// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: salad/grpc/saladcloud_job_queue_worker/v1alpha/service_v1alpha.proto

package queues

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a request to the `AcceptJobs` method.
type AcceptJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the currently running job. Optional. This should be
	// specified when the worker reconnects after a transient error and has not
	// yet completed or rejected the job.
	CurrentJobId  string `protobuf:"bytes,1,opt,name=current_job_id,json=currentJobId,proto3" json:"current_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptJobsRequest) Reset() {
	*x = AcceptJobsRequest{}
	mi := &file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptJobsRequest) ProtoMessage() {}

func (x *AcceptJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptJobsRequest.ProtoReflect.Descriptor instead.
func (*AcceptJobsRequest) Descriptor() ([]byte, []int) {
	return file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptJobsRequest) GetCurrentJobId() string {
	if x != nil {
		return x.CurrentJobId
	}
	return ""
}

// Represents a response from the `AcceptJobs` method.
type AcceptJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stream message.
	//
	// Types that are valid to be assigned to Message:
	//
	//	*AcceptJobsResponse_Heartbeat
	//	*AcceptJobsResponse_Job
	Message       isAcceptJobsResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptJobsResponse) Reset() {
	*x = AcceptJobsResponse{}
	mi := &file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptJobsResponse) ProtoMessage() {}

func (x *AcceptJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptJobsResponse.ProtoReflect.Descriptor instead.
func (*AcceptJobsResponse) Descriptor() ([]byte, []int) {
	return file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptJobsResponse) GetMessage() isAcceptJobsResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AcceptJobsResponse) GetHeartbeat() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Message.(*AcceptJobsResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AcceptJobsResponse) GetJob() *Job {
	if x != nil {
		if x, ok := x.Message.(*AcceptJobsResponse_Job); ok {
			return x.Job
		}
	}
	return nil
}

type isAcceptJobsResponse_Message interface {
	isAcceptJobsResponse_Message()
}

type AcceptJobsResponse_Heartbeat struct {
	// An empty message used to health check the stream. The worker should
	// ignore this message.
	Heartbeat *emptypb.Empty `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AcceptJobsResponse_Job struct {
	// The next job to be executed. The worker must call either
	// `CompleteJob` or `RejectJob` with the result.
	Job *Job `protobuf:"bytes,2,opt,name=job,proto3,oneof"`
}

func (*AcceptJobsResponse_Heartbeat) isAcceptJobsResponse_Message() {}

func (*AcceptJobsResponse_Job) isAcceptJobsResponse_Message() {}

// Represents a job.
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the job.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// The port number of the HTTP server.
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// The HTTP request path.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// The HTTP request body.
	Input         []byte `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Job) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Job) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

// Represents a request to the `CompleteJob` method.
type CompleteJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the job.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// The HTTP response body.
	Output        []byte `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobRequest) Reset() {
	*x = CompleteJobRequest{}
	mi := &file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobRequest) ProtoMessage() {}

func (x *CompleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobRequest.ProtoReflect.Descriptor instead.
func (*CompleteJobRequest) Descriptor() ([]byte, []int) {
	return file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteJobRequest) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

// Represents a request to the `RejectJob` method.
type RejectJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the job.
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectJobRequest) Reset() {
	*x = RejectJobRequest{}
	mi := &file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectJobRequest) ProtoMessage() {}

func (x *RejectJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectJobRequest.ProtoReflect.Descriptor instead.
func (*RejectJobRequest) Descriptor() ([]byte, []int) {
	return file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescGZIP(), []int{4}
}

func (x *RejectJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto protoreflect.FileDescriptor

const file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDesc = "" +
	"\n" +
	"Dsalad/grpc/saladcloud_job_queue_worker/v1alpha/service_v1alpha.proto\x12.salad.grpc.saladcloud_job_queue_worker.v1alpha\x1a\x1bgoogle/protobuf/empty.proto\"9\n" +
	"\x11AcceptJobsRequest\x12$\n" +
	"\x0ecurrent_job_id\x18\x01 \x01(\tR\fcurrentJobId\"\xa0\x01\n" +
	"\x12AcceptJobsResponse\x126\n" +
	"\theartbeat\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\theartbeat\x12G\n" +
	"\x03job\x18\x02 \x01(\v23.salad.grpc.saladcloud_job_queue_worker.v1alpha.JobH\x00R\x03jobB\t\n" +
	"\amessage\"Z\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05input\x18\x04 \x01(\fR\x05input\"C\n" +
	"\x12CompleteJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\")\n" +
	"\x10RejectJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId2\x81\x03\n" +
	"\x15JobQueueWorkerService\x12\x95\x01\n" +
	"\n" +
	"AcceptJobs\x12A.salad.grpc.saladcloud_job_queue_worker.v1alpha.AcceptJobsRequest\x1aB.salad.grpc.saladcloud_job_queue_worker.v1alpha.AcceptJobsResponse0\x01\x12i\n" +
	"\vCompleteJob\x12B.salad.grpc.saladcloud_job_queue_worker.v1alpha.CompleteJobRequest\x1a\x16.google.protobuf.Empty\x12e\n" +
	"\tRejectJob\x12@.salad.grpc.saladcloud_job_queue_worker.v1alpha.RejectJobRequest\x1a\x16.google.protobuf.EmptyB\xae\x02\n" +
	"2com.salad.grpc.saladcloud_job_queue_worker.v1alphaB\x13ServiceV1alphaProtoP\x01Z\x14internal/apis/queues\xa2\x02\x03SGS\xaa\x02+Salad.Grpc.SaladcloudJobQueueWorker.V1alpha\xca\x02+Salad\\Grpc\\SaladcloudJobQueueWorker\\V1alpha\xe2\x027Salad\\Grpc\\SaladcloudJobQueueWorker\\V1alpha\\GPBMetadata\xea\x02.Salad::Grpc::SaladcloudJobQueueWorker::V1alphab\x06proto3"

var (
	file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescOnce sync.Once
	file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescData []byte
)

func file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescGZIP() []byte {
	file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescOnce.Do(func() {
		file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDesc), len(file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDesc)))
	})
	return file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDescData
}

var file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_goTypes = []any{
	(*AcceptJobsRequest)(nil),  // 0: salad.grpc.saladcloud_job_queue_worker.v1alpha.AcceptJobsRequest
	(*AcceptJobsResponse)(nil), // 1: salad.grpc.saladcloud_job_queue_worker.v1alpha.AcceptJobsResponse
	(*Job)(nil),                // 2: salad.grpc.saladcloud_job_queue_worker.v1alpha.Job
	(*CompleteJobRequest)(nil), // 3: salad.grpc.saladcloud_job_queue_worker.v1alpha.CompleteJobRequest
	(*RejectJobRequest)(nil),   // 4: salad.grpc.saladcloud_job_queue_worker.v1alpha.RejectJobRequest
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
}
var file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_depIdxs = []int32{
	5, // 0: salad.grpc.saladcloud_job_queue_worker.v1alpha.AcceptJobsResponse.heartbeat:type_name -> google.protobuf.Empty
	2, // 1: salad.grpc.saladcloud_job_queue_worker.v1alpha.AcceptJobsResponse.job:type_name -> salad.grpc.saladcloud_job_queue_worker.v1alpha.Job
	0, // 2: salad.grpc.saladcloud_job_queue_worker.v1alpha.JobQueueWorkerService.AcceptJobs:input_type -> salad.grpc.saladcloud_job_queue_worker.v1alpha.AcceptJobsRequest
	3, // 3: salad.grpc.saladcloud_job_queue_worker.v1alpha.JobQueueWorkerService.CompleteJob:input_type -> salad.grpc.saladcloud_job_queue_worker.v1alpha.CompleteJobRequest
	4, // 4: salad.grpc.saladcloud_job_queue_worker.v1alpha.JobQueueWorkerService.RejectJob:input_type -> salad.grpc.saladcloud_job_queue_worker.v1alpha.RejectJobRequest
	1, // 5: salad.grpc.saladcloud_job_queue_worker.v1alpha.JobQueueWorkerService.AcceptJobs:output_type -> salad.grpc.saladcloud_job_queue_worker.v1alpha.AcceptJobsResponse
	5, // 6: salad.grpc.saladcloud_job_queue_worker.v1alpha.JobQueueWorkerService.CompleteJob:output_type -> google.protobuf.Empty
	5, // 7: salad.grpc.saladcloud_job_queue_worker.v1alpha.JobQueueWorkerService.RejectJob:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_init() }
func file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_init() {
	if File_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto != nil {
		return
	}
	file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes[1].OneofWrappers = []any{
		(*AcceptJobsResponse_Heartbeat)(nil),
		(*AcceptJobsResponse_Job)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDesc), len(file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_goTypes,
		DependencyIndexes: file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_depIdxs,
		MessageInfos:      file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_msgTypes,
	}.Build()
	File_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto = out.File
	file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_goTypes = nil
	file_salad_grpc_saladcloud_job_queue_worker_v1alpha_service_v1alpha_proto_depIdxs = nil
}
