// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: salad/grpc/saladcloud_job_queue_worker/v1alpha/service_v1alpha.proto

package queues

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	JobQueueWorkerService_AcceptJobs_FullMethodName  = "/salad.grpc.saladcloud_job_queue_worker.v1alpha.JobQueueWorkerService/AcceptJobs"
	JobQueueWorkerService_CompleteJob_FullMethodName = "/salad.grpc.saladcloud_job_queue_worker.v1alpha.JobQueueWorkerService/CompleteJob"
	JobQueueWorkerService_RejectJob_FullMethodName   = "/salad.grpc.saladcloud_job_queue_worker.v1alpha.JobQueueWorkerService/RejectJob"
)

// JobQueueWorkerServiceClient is the client API for JobQueueWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobQueueWorkerServiceClient interface {
	// Starts a long-running stream to accept jobs. At any given time, the
	// worker should have at most one stream open. The worker will receive at
	// most one job at a time. The service will wait until the worker completes
	// or rejects the job, by calling `CompleteJob` or `RejectJob`, before
	// sending the next job. The worker is considered available to accept jobs
	// as long as the stream is open. This may return an error with a `NotFound`
	// status code if the currently running job no longer exists.
	AcceptJobs(ctx context.Context, in *AcceptJobsRequest, opts ...grpc.CallOption) (JobQueueWorkerService_AcceptJobsClient, error)
	// Completes a job.
	CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Rejects a job.
	RejectJob(ctx context.Context, in *RejectJobRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type jobQueueWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobQueueWorkerServiceClient(cc grpc.ClientConnInterface) JobQueueWorkerServiceClient {
	return &jobQueueWorkerServiceClient{cc}
}

func (c *jobQueueWorkerServiceClient) AcceptJobs(ctx context.Context, in *AcceptJobsRequest, opts ...grpc.CallOption) (JobQueueWorkerService_AcceptJobsClient, error) {
	stream, err := c.cc.NewStream(ctx, &JobQueueWorkerService_ServiceDesc.Streams[0], JobQueueWorkerService_AcceptJobs_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &jobQueueWorkerServiceAcceptJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JobQueueWorkerService_AcceptJobsClient interface {
	Recv() (*AcceptJobsResponse, error)
	grpc.ClientStream
}

type jobQueueWorkerServiceAcceptJobsClient struct {
	grpc.ClientStream
}

func (x *jobQueueWorkerServiceAcceptJobsClient) Recv() (*AcceptJobsResponse, error) {
	m := new(AcceptJobsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobQueueWorkerServiceClient) CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobQueueWorkerService_CompleteJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobQueueWorkerServiceClient) RejectJob(ctx context.Context, in *RejectJobRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobQueueWorkerService_RejectJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobQueueWorkerServiceServer is the server API for JobQueueWorkerService service.
// All implementations must embed UnimplementedJobQueueWorkerServiceServer
// for forward compatibility
type JobQueueWorkerServiceServer interface {
	// Starts a long-running stream to accept jobs. At any given time, the
	// worker should have at most one stream open. The worker will receive at
	// most one job at a time. The service will wait until the worker completes
	// or rejects the job, by calling `CompleteJob` or `RejectJob`, before
	// sending the next job. The worker is considered available to accept jobs
	// as long as the stream is open. This may return an error with a `NotFound`
	// status code if the currently running job no longer exists.
	AcceptJobs(*AcceptJobsRequest, JobQueueWorkerService_AcceptJobsServer) error
	// Completes a job.
	CompleteJob(context.Context, *CompleteJobRequest) (*emptypb.Empty, error)
	// Rejects a job.
	RejectJob(context.Context, *RejectJobRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedJobQueueWorkerServiceServer()
}

// UnimplementedJobQueueWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJobQueueWorkerServiceServer struct {
}

func (UnimplementedJobQueueWorkerServiceServer) AcceptJobs(*AcceptJobsRequest, JobQueueWorkerService_AcceptJobsServer) error {
	return status.Errorf(codes.Unimplemented, "method AcceptJobs not implemented")
}
func (UnimplementedJobQueueWorkerServiceServer) CompleteJob(context.Context, *CompleteJobRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteJob not implemented")
}
func (UnimplementedJobQueueWorkerServiceServer) RejectJob(context.Context, *RejectJobRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectJob not implemented")
}
func (UnimplementedJobQueueWorkerServiceServer) mustEmbedUnimplementedJobQueueWorkerServiceServer() {}

// UnsafeJobQueueWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobQueueWorkerServiceServer will
// result in compilation errors.
type UnsafeJobQueueWorkerServiceServer interface {
	mustEmbedUnimplementedJobQueueWorkerServiceServer()
}

func RegisterJobQueueWorkerServiceServer(s grpc.ServiceRegistrar, srv JobQueueWorkerServiceServer) {
	s.RegisterService(&JobQueueWorkerService_ServiceDesc, srv)
}

func _JobQueueWorkerService_AcceptJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AcceptJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobQueueWorkerServiceServer).AcceptJobs(m, &jobQueueWorkerServiceAcceptJobsServer{stream})
}

type JobQueueWorkerService_AcceptJobsServer interface {
	Send(*AcceptJobsResponse) error
	grpc.ServerStream
}

type jobQueueWorkerServiceAcceptJobsServer struct {
	grpc.ServerStream
}

func (x *jobQueueWorkerServiceAcceptJobsServer) Send(m *AcceptJobsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _JobQueueWorkerService_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobQueueWorkerServiceServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobQueueWorkerService_CompleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobQueueWorkerServiceServer).CompleteJob(ctx, req.(*CompleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobQueueWorkerService_RejectJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobQueueWorkerServiceServer).RejectJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobQueueWorkerService_RejectJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobQueueWorkerServiceServer).RejectJob(ctx, req.(*RejectJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobQueueWorkerService_ServiceDesc is the grpc.ServiceDesc for JobQueueWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobQueueWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "salad.grpc.saladcloud_job_queue_worker.v1alpha.JobQueueWorkerService",
	HandlerType: (*JobQueueWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompleteJob",
			Handler:    _JobQueueWorkerService_CompleteJob_Handler,
		},
		{
			MethodName: "RejectJob",
			Handler:    _JobQueueWorkerService_RejectJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AcceptJobs",
			Handler:       _JobQueueWorkerService_AcceptJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "salad/grpc/saladcloud_job_queue_worker/v1alpha/service_v1alpha.proto",
}
